//main
export const SET_COMMUNITY = 'SET_COMMUNITY';
export const SET_NAME = 'SET_NAME';
export const SET_INCIDENTS = 'SET_INCIDENTS';
export const SET_TITLES = 'SET_TITLES';
export const SET_DESCRIPTIONS = 'SET_DESCRIPTIONS';
export const SET_INCIDENTS_COUNT = 'SET_INCIDENTS_COUNT';
export const SET_FETCHING_INCIDENTS = 'SET_FETCHING_INCIDENTS';
export const SET_APPROVED = 'SET_APPROVED';

export const ADD_INCIDENTS = 'ADD_INCIDENTS';
export const ADD_INCIDENTS_PAGES_LOADED = 'ADD_INCIDENTS_PAGES_LOADED';

export const REPLACE_PRODUCTS = 'REPLACE_PRODUCTS';
export const REPLACE_HAZARDS = 'REPLACE_HAZARDS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_HAZARD = 'ADD_HAZARD';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_HAZARD = 'EDIT_HAZARD';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const REMOVE_HAZARD = 'REMOVE_HAZARD';

// filters
export const LOAD_CURATION = 'LOAD_CURATION';
export const SET_LOADING_CURATION = 'SET_LOADING_CURATION';
export const SET_REMOTE_PRODUCTS = 'SET_REMOTE_PRODUCTS';
export const SET_ORIGINAL_SOURCES = 'SET_ORIGINAL_SOURCES';
export const SET_SELECTED_REMOTE_PRODUCTS = 'SET_SELECTED_REMOTE_PRODUCTS';
export const SET_SELECTED_ORIGINAL_SOURCES = 'SET_SELECTED_ORIGINAL_SOURCES';
export const SET_SELECTED_SUPPLIER = 'SET_SELECTED_SUPPLIER';
export const SET_SELECTED_DATE_RANGE = 'SET_SELECTED_DATE_RANGE';

// taxonomies
export const SET_PRODUCTS_TAXONOMY = 'SET_PRODUCTS_TAXONOMY';
export const SET_HAZARDS_TAXONOMY = 'SET_HAZARDS_TAXONOMY';
export const SET_COUNTRIES_TAXOOMY = 'SET_COUNTRIES_TAXOOMY';
