//main
export const SET_COMMUNITY = 'SET_COMMUNITY';
export const SET_INCIDENTS = 'SET_INCIDENTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_HAZARDS = 'SET_HAZARDS';
export const SET_TITLES = 'SET_TITLES';
export const SET_DESCRIPTIONS = 'SET_DESCRIPTIONS';
export const SET_INCIDENTS_COUNT = 'SET_INCIDENTS_COUNT';
export const SET_INCIDENTS_COUNTS_PER_YEAR = 'SET_INCIDENTS_COUNTS_PER_YEAR';
export const SET_FETCHING_INCIDENTS = 'SET_FETCHING_INCIDENTS';

export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_HAZARDS = 'ADD_HAZARDS';
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS';
export const REMOVE_HAZARDS = 'REMOVE_HAZARDS';
export const ADD_INCIDENTS = 'ADD_INCIDENTS';
export const ADD_INCIDENTS_PAGES_LOADED = 'ADD_INCIDENTS_PAGES_LOADED';
